#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/dsn.jar:$APPDIR/lib/gimap.jar:$APPDIR/lib/imap.jar:$APPDIR/lib/mail.jar:$APPDIR/lib/mailapi.jar:$APPDIR/lib/pop3.jar:$APPDIR/lib/smtp.jar:$APPDIR/lib/VoiceDictationSentToEmail.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-amd64.jar:$APPDIR/lib/gluegen-rt-natives-linux-amd64.jar:$APPDIR/lib/G4P.jar:$APPDIR/lib/jl1.0.jar:$APPDIR/lib/jsminim.jar:$APPDIR/lib/minim.jar:$APPDIR/lib/mp3spi1.9.4.jar:$APPDIR/lib/tritonus_aos.jar:$APPDIR/lib/tritonus_share.jar" VoiceDictationSentToEmail "$@"
